### ISSUE TITLE
gRPC interception: add ability to autofill `resource_name`

### ISSUE THREAD

**Issue by NoamRabbani** [abcxyz/lumberjack#126]
`resource_name` is the only "required field" we cannot autofill. However, in some cases, it could be possible to autofill this field and write an audit log with zero application code change. We should add a config option that tells the interceptor to autofill `resource_name` for a given RPC method. For details, see the [design doc section on inferring the `resource_name`](https://docs.google.com/document/d/1aLtquVaYeOqOMvu87ux1Ob79aFMjHqFdUgOfpyT08RY/edit#bookmark=id.8mxgf43pzido)

**Comment by yolocs** [comment]
No plan to fix.
