### ISSUE TITLE
Implement long term strategy for releasing images

### ISSUE THREAD

**Issue by verbanicm** [abcxyz/lumberjack#184]
Currently we are hosting images in `lumberjack-dev-infra` project to support standing up Verily. The long term strategy should be defined and implemented before this is considered "completed".

See releasing artifact documents at https://docs.google.com/document/d/1zfGlXU-sVI70oPRIi4BEOGuZOA54VyG3LnyNS43KXUw.

**Comment by yolocs** [comment]
How to release artifacts is now a horizontal question. Thus, clean it up from lumberjack.
