### ISSUE TITLE
Consider GitHub Actions to keep generated

### ISSUE THREAD

**Issue by myurtoglu** [abcxyz/lumberjack#223]
As we update the protos in [here](https://github.com/abcxyz/lumberjack/tree/main/protos/v1alpha1), there is always the chance of forgetting to update the go generated protos in [here, the files with the extension .pb.go](https://github.com/abcxyz/lumberjack/tree/main/clients/go/apis/v1alpha1) (happened to me and a reviewer caught it).

It may be worth adding a new GitHub action that runs `protoc` + `gofmt`/`goimports` on the proto directory [like this shell script](https://github.com/abcxyz/lumberjack/blob/main/scripts/gen_protos.sh) and compares it against the checked in `.pb.go` files. If a difference is found, the action can fail with a message asking to update the checked in protos.

**Comment by yolocs** [comment]
This has not been a problem so far. Usually whoever updates the proto will regenerate the code. We should only consider this if it ever becomes a real issue.
