### ISSUE TITLE
Bug: Integration Tests are Flaky

### ISSUE THREAD

**Issue by raserva** [abcxyz/lumberjack#256]
This change, which is tiny, is facing multiple integ test failures: https://github.com/abcxyz/lumberjack/pull/255

I assume by re-running, they will likely pass as the failures are on the java side, which isn't impacted. I have also seen failures due to the key not being ready in time. we should work to reduce the flakiness, as when the integ tests take 10 mins to run, it seriously slows down development if we have to run multiple times, and degrades confidence in the test suite as a whole.

**Comment by raserva** [comment]
I can confirm on the change above, after re-running twice, the integ tests passed.

**Comment by raserva** [comment]
2 PRs with changes intended to help with the flakiness. 

[One increases the timeout on the go linter](https://github.com/abcxyz/pkg/pull/29)

[As part of another PR, the maximum retries are increased when checking for audit logs.](https://github.com/abcxyz/lumberjack/pull/254/files#diff-0f13d7606dbb4b32d651c81e8dcb5cc6766dafb586160715a20b6e98386c5d67L30)

**Comment by yolocs** [comment]
@raserva With the changes in the 2 PRs, are there any immediate actions we should take? Is integ test still flaky?

**Comment by yolocs** [comment]
Close for now since we haven't since any more flakiness after the previous effort.
