### ISSUE TITLE
Followup ideas for https://github.com/abcxyz/lumberjack/pull/254

### ISSUE THREAD

**Issue by yolocs** [abcxyz/lumberjack#260]
- The expected header name is `justification_token`. But header name is usually concatenated with `-` rather than `_`. It's more natural to have `justification-token` instead.
- Optional: `justification_token` is not a standard header. To avoid potential conflicts with other headers, we probably should add it's a token from **abcxyz/jvs**. E.g. `abcxyz-justification`. The practice is common, e.g. `x-envoy-external-address`
- We need to handle breakglass token differently
- The token validator is named as `JWTValidator` (general) but it's only used for validating justification token. A better name would be `JustificationTokenValidator`

cc: @raserva

**Comment by raserva** [comment]
header name change: https://github.com/abcxyz/lumberjack/pull/267

**Comment by yolocs** [comment]
Evenything here should already be fixed.
