### ISSUE TITLE
Feat: Change justification tokens to be struct rather than string. 

### ISSUE THREAD

**Issue by raserva** [abcxyz/lumberjack#265]
Setting as string is not query friendly. I think we should convert it a `*structpb.Value`, see example: https://github.com/abcxyz/lumberjack/blob/main/clients/go/pkg/audit/runtime.go#L251

_Originally posted by @yolocs in https://github.com/abcxyz/lumberjack/pull/261#discussion_r929354662_

**Comment by yolocs** [comment]
Still need to update java client
