### ISSUE TITLE
combine jvs related config into one object( java & golang)

### ISSUE THREAD

**Issue by capri-xiyue** [abcxyz/lumberjack#280]
### TL;DR

combine jvs related config into one object for **_both Java and Golang_**

### Detailed design
example PR(Golang): https://github.com/abcxyz/lumberjack/pull/284

_No response_

**Comment by yolocs** [comment]
Can this be closed? @capri-xiyue

**Comment by capri-xiyue** [comment]
> Can this be closed? @capri-xiyue

missing java part

**Comment by yolocs** [comment]
cc: @sqin2019
