### ISSUE TITLE
JVS client cannot be initialized with raw JVS client config directly

### ISSUE THREAD

**Issue by yolocs** [abcxyz/lumberjack#297]
### TL;DR

We provide a raw JVS config to initialize a JVS client

https://github.com/abcxyz/lumberjack/blob/main/clients/go/pkg/auditopt/config.go#L262

It will fail because the new config defaulting logic in JVS client requires the use `envconfig`. Constructing a JVSConfig directly won't set defaults.

### Environment Details

```markdown
See above
```

**Comment by sethvargo** [comment]
@yolocs do you think jvs should provide a `NewClient` option that initializes things?

**Comment by yolocs** [comment]
Probably. Although I don't necessarily see it as "lacking option" problem since the raw config is already kind of an option. I see it more as a "lacking a lib to load config with defaults" problem.
See context in https://github.com/abcxyz/jvs/issues/104. Maybe it's a good idea to add that to `pkg`.

**Comment by yolocs** [comment]
Send a PR for the idea: https://github.com/abcxyz/pkg/pull/33

**Comment by yolocs** [comment]
PR in pkg merged. Will create a new issue to adopt the new lib in lumberjack
