### ISSUE TITLE
Java Client doesn't seem to respect Env Vars?

### ISSUE THREAD

**Issue by crwilcox** [abcxyz/lumberjack#333]
### TL;DR

I was working with another Googler and we were trying to use the java client. We had set the env vars for project
```
export AUDIT_CLIENT_BACKEND_CLOUDLOGGING_PROJECT="oursupersecretproject"
```

And then ran the client.  It failed with permission_denied.

we reran after making /etc/lumberjack/config.yaml
```
backend:
  cloudlogging:
    project: oursupersecretproject
```

And it ran to completion.

Is java implemented to respect the env vars?

### Expected behavior

Expected a log write

### Observed behavior

perm denied

### Environment Details

```markdown
GCE VM, without project set, I think it may be using the VM's project, not the target project? likely unrelated to not respecting the cloud logging
```

**Comment by crwilcox** [comment]
@mercereau FYI

**Comment by yolocs** [comment]
There is one bug and one documentation issue here.

https://github.com/abcxyz/lumberjack/blob/49f1d6e8e1224d0c63926f1601afd16c536bf7b7/clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/config/CloudLoggingConfiguration.java#L28 didn't really have `AUDIT_CLIENT_` prefix and that was a mistake.

Java client by default looks up the config in its resources e.g. https://github.com/abcxyz/lumberjack/blob/49f1d6e8e1224d0c63926f1601afd16c536bf7b7/clients/java-logger/shell/src/main/resources/audit_logging.yml. The doc here https://github.com/abcxyz/lumberjack/blob/49f1d6e8e1224d0c63926f1601afd16c536bf7b7/docs/config.md was not updated accordingly. The client usage doc is: https://github.com/abcxyz/lumberjack/blob/92f429c9147e9ce6edf7e4c3bbe71550cbeb5b1c/docs/clients.md#java.
