### ISSUE TITLE
Justification validation error should be handled as invalid request

### ISSUE THREAD

**Issue by yolocs** [abcxyz/lumberjack#371]
https://github.com/abcxyz/lumberjack/blob/main/clients/go/pkg/justification/processor.go. Any error returned from this processor should be considered https://github.com/abcxyz/lumberjack/blob/main/clients/go/pkg/audit/errors.go#L24

Such error shouldn't be ignored in "best effort" logging mode.

**Comment by sethvargo** [comment]
I think we should try to separate the error that is returned from the behavior in best effort logging mode.

I would prefer if we returned concrete error constants in the processor and kept the logic for whether those errors can be "ignored" maintained separately. Thoughts?

**Comment by yolocs** [comment]
Agreed.

1. We already return concrete errors when it matters, e.g. `ErrInvalidRequest ` when the request is invalid: https://github.com/abcxyz/lumberjack/blob/main/clients/go/pkg/audit/validation.go#L29
2. In the client, we need better handling of these concrete errors. We only handle `ErrFailedPrecondition` today. And remaining errors are considered "ignorable", which is not correct.
