### ISSUE TITLE
Test could pass even wantErr isn't the type we expected

### ISSUE THREAD

**Issue by sailorlqh** [abcxyz/lumberjack#399]
The PrincipleEmail for [this case](https://github.com/abcxyz/lumberjack/blob/main/clients/go/pkg/audit/validation_test.go#L107) would be treated as malformed by this [function](https://github.com/abcxyz/lumberjack/blob/main/clients/go/pkg/audit/validation.go#L71).

Therefore, in this test case, even serviceName is provided, we would still got an error.

**Comment by sethvargo** [comment]
https://github.com/abcxyz/lumberjack/pull/400
