### ISSUE TITLE
Move tests logging serve failure to error on it in processor_test, config_test

### ISSUE THREAD

**Issue by crwilcox** [abcxyz/lumberjack#47]
Search for "TODO: it may be worth validating this scenario. #47" in the source code.

For example:
https://github.com/abcxyz/lumberjack/pull/36/files#diff-e6a5da49af5dca721e705f73a5260e07efcad17ca1a0f49dbd9ec5f044d70f0dR329

https://github.com/abcxyz/lumberjack/pull/36/files#diff-3a18f21fa58cf985b8d8a3f69b25141aa98520c24fe8c1433005851913323855R282

These were gaps found during linting that now at least check err, though we don't do anything with it at this time

**Comment by yolocs** [comment]
This was fixed
